### ISSUE TITLE
mousai

### ISSUE THREAD

**Issue by Alphonce-omondi** [SeaDve/Mousai#103]
- io.github.seadve.Mousai 0.7.5
- Flatpak: false

- Language: en_US.UTF-8, en_US, en.UTF-8, en, C

- Distribution: Ubuntu Core 22
- Desktop Session: ubuntu
- Display Server: wayland

- GTK 4.10.4
- Libadwaita 1.3.3
- Libsoup 3.4.2
- GStreamer 1.20.3

**Comment by soumyaDghosh** [comment]
@Alphonce-omondi kindly explain what issue are you facing. Are you not able to play the songs within the app?

**Comment by SeaDve** [comment]
I'm gonna close this for now since the information given does not give much context or the problem. Feel free to re-open it though with the required information. Thanks!
