### ISSUE TITLE
Does not ask for microphone access permission

### ISSUE THREAD

**Issue by aryasheikhi** [SeaDve/Mousai#108]
**Affected version**

- io.github.seadve.Mousai 0.7.5
- Flatpak: false

- Language: en_US.UTF-8, en_US, en.UTF-8, en, C

- Distribution: Ubuntu Core 22
- Desktop Session: ubuntu
- Display Server: wayland

- GTK 4.12.2
- Libadwaita 1.4.0
- Libsoup 3.4.3
- GStreamer 1.20.3

**Bug summary**

I installed the app using snap. After trying to recognize a song, the app did not respond by accessing microphone data. Instead it threw an error indicating "Received Other Permanent Error"

**Steps to reproduce**

1. Install using Snap on Ubuntu 22.04.03
2. Try listening
3. Application does not get microphone access and

**Comment by SeaDve** [comment]
I'm not sure how microphone access works under snap, so I'm going to ping @soumyaDghosh here.

**Comment by soumyaDghosh** [comment]
@aryasheikhi I am requesting some extra details here to debug. 

Outputs of the below commands.

1. `snap version`
2. `snap connections mousai`

**Comment by SeaDve** [comment]
> if I am not wrong, mousai uses portals to access the microphone, but with Ubuntu 22.04 it probably doesn't have that latest portal, which is probably making this error. Kindly correct me if I am wrong.

Mousai uses the gstreamer device provider and fallbacks to pulseaudio. While I'd like for it to use a portal to access the microphone, it currently does not, and I think there is no microphone portal at the present.

**Comment by aryasheikhi** [comment]
Thanks for the reply
@soumyaDghosh 
As for snap version
```
➜  ~ snap --version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  6.2.0-36-generic
```
as for snap connections
![image](https://github.com/SeaDve/Mousai/assets/46236263/b18434f0-d4eb-46b6-8024-40f883d44334)

**Comment by soumyaDghosh** [comment]
For the snap, I'll try to add the `audio-record` plug. But I see you're using generic kernels. Are they supported by ubuntu?

**Comment by SeaDve** [comment]
The logs would also be useful from Mousai side

**Comment by soumyaDghosh** [comment]
> The logs would also be useful from Mousai side

I am actually very curious about them. @SeaDve does you app need access to microphone separately? I think then it's my fault.

**Comment by SeaDve** [comment]
> does you app need access to microphone separately?

I'm not sure what exactly you mean, but on Flatpak side, you at least need the pulseaudio socket, bot when recording from microphone or desktop audio

**Comment by soumyaDghosh** [comment]
Umm.. seems that snap has it. But, TBH, the snap was never to recognize any song via microphone. But, I never found any error log regarding not able to access microphone. It also looked like that it's recording audio. Cause it spiked while high talks.

![image](https://github.com/SeaDve/Mousai/assets/72045785/9a067d7c-5b3c-4f50-809d-c868ae002ac6)

**Comment by SeaDve** [comment]
I'm gonna close this for now since the information given does not give much context or the problem. Feel free to re-open it though with the required information. Thanks!
