### ISSUE TITLE
Spongelab 04/01/2024

### ISSUE THREAD

**Issue by SpongeLab64** [SeaDve/Mousai#116]
**Affected version**

**Bug summary**

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

- io.github.seadve.Mousai 0.7.5
- Flatpak: false

- Language: en_GB, en, C

- Distribution: Ubuntu Core 22
- Desktop Session: plasma
- Display Server: x11

- GTK 4.12.2
- Libadwaita 1.4.0
- Libsoup 3.4.3
- GStreamer 1.20.3

**Comment by SeaDve** [comment]
I'm gonna close this for now since the information given does not give much context or the problem. Feel free to re-open it though with the required information. Thanks!
