### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by talivan5** [SeaDve/Mousai#120]
**Affected version**

**Bug summary**

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

**Comment by SeaDve** [comment]
Thanks for taking the time to report this issue. Unfortunately, this report isn't very useful because it doesn't include a complete and easy to understand description of the issue. Please update the issue report to include a more detailed description and feel free to reopen the issue.
