### ISSUE TITLE
Song bar background blur causes huge GPU usage

### ISSUE THREAD

**Issue by meybonomme** [SeaDve/Mousai#121]
**Affected version**
0.7.6

**Bug summary**
Music playback causing huge GPU usage, the entire desktop will lag strongly.

**Relevant logs, screenshots, screencasts, etc.**
[Screencast from 2024-02-06 19-43-38.webm](https://github.com/SeaDve/Mousai/assets/147217565/879bf25e-ecea-40e9-bce6-6d78aa730937)

Fedora 39
GNOME 45.3
Wayland
Intel UHD Graphics 620

**Comment by SeaDve** [comment]
This is likely caused by the blur on the player bar, not the playback itself. To confirm, if you are familiar with using the inspector, you can hide it and see if it is still reproducible.

**Comment by meybonomme** [comment]
Now I know how to use GTK Inspector.
Please give me instructions, how to hide player bar blur. I can't find it myself.

**Comment by SeaDve** [comment]
Here's a quick screencast.

[Kooha-2024-02-07-22-05-13.webm](https://github.com/SeaDve/Mousai/assets/64297935/5db82d52-bc25-4328-ba79-8b268f191070)

After setting visible to unchecked, hiding `SongBar`, try reproducing the issue.

**Comment by meybonomme** [comment]
Thank you!

If songbar is hided, issue is gone and GPU usage is 0%.
Personally I don't like blurring in GNOME apps at all, native GNOME apps doesn't use also blurring.

Can you remove songbar blur and coloring from cover picture completely? It's much more resource friendly and much nicer and cleaner. I like very much simplified and clean look of GNOME native apps.

**Comment by SeaDve** [comment]
Thanks too for testing and confirming!

> Can you remove songbar blur and coloring from cover picture completely? It's much more resource friendly and much nicer and cleaner. I like very much simplified and clean look of GNOME native apps.

I personally have been contemplating about it too a few months ago, regarding aesthetic and performance issues. 

On the other hand, the blur issue is a bug in GTK or somewhere deeper down the stack, it is possible to keep it without impacting performance, but I get your point on making the UI cleaner and simpler.

**Comment by meybonomme** [comment]
> On the other hand, the blur issue is a bug in GTK or somewhere deeper down the stack...

I can understand, but you can't wait and hope this upstream issue will be fixed any time soon. And simpler and cleaner UI is in my opinion much nicer anyway, more "gnome-ish".

If you are interested, I have already few other UI improvements in my mind :wink:

**Comment by SeaDve** [comment]
> If you are interested, I have already few other UI improvements in my mind 😉
