### ISSUE TITLE
Mousai no reconoce ninguna canción y abre la ventana de "incidente". No manejo bien el tema de Mousai ni GitHub. No hablo inglés, solamente español.

### ISSUE THREAD

**Issue by ballerod** [SeaDve/Mousai#128]
**Affected version**

**Bug summary**

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

**Comment by SeaDve** [comment]
I'm gonna close this for now since the information given does not give much context or the problem. Feel free to re-open it though with the required information. Thanks!
