### ISSUE TITLE
[Feature Request] Export to text

### ISSUE THREAD

**Issue by lonix1** [SeaDve/Mousai#142]
### Feature summary
An "Export Tracks" feature in the hamburger menu.

### How would you like it to work
I've recognised many tracks. Now it's necessary to click them one-by-one and hunt for a place to listen to or buy the tracks. That is significant effort, so I've just given up.

It would be more convenient to simply "export all" to text which I can then use myself to find the tracks.

It doesn't need to save to a text or csv file - it could simply put the data in the clipboard.

### Relevant links, screenshots, screencasts, etc.
n/a

Thanks for making this realy useful app!

**Comment by SeaDve** [comment]
This is possible in the currently released version. You can select all tracks, then click copy. The copied string should contain a list of track title + artist.
