### ISSUE TITLE
App doesn't launch: Can't open display

### ISSUE THREAD

**Issue by sallyahaj** [SeaDve/Mousai#2]
Hello there,
I have installed it from flathub, but when I try to run it I get this message:

`(io.github.seadve.Mousai:2): Gtk-WARNING **: 20:36:51.392: cannot open display: 
`
I am using Fedora 34 Gnome 40, GTK4.
Thank you.

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/issues/32

This might be related and possible fix.

**Comment by SeaDve** [comment]
Since this is not an issue with Mousai itself, gonna close this, but feel free to reopen, thanks!
