### ISSUE TITLE
Respect dark theme

### ISSUE THREAD

**Issue by aronkvh** [SeaDve/Mousai#31]
Hi and thanks for the great app.
I'm using KDE Plasma and even though my gtk theme is breeze-dark , the app uses adwaita light.
I understand if you don't want the UI to be messed up by themes, but could you make it support dark/light themes?

**Comment by SeaDve** [comment]
Hi, thanksss

Unfortunately, the underlying library, libadwaita, doesn't support custom theme nor dark theme for now, and I can't do much about it without doing hacky way.

You can force it though to make it use a dark theme or any other themes.

You can also check https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/224.

**Comment by SeaDve** [comment]
It also doesn't respect on other DE such as gnome, so it's not entirely on plasma

**Comment by SeaDve** [comment]
closing this since i cant do much here
