### ISSUE TITLE
Error when building from AUR on aarch64

### ISSUE THREAD

**Issue by CoderThomasB** [SeaDve/Mousai#36]
It would be really nice to be able to use this app on a Linux phone like the Pine phone but the AUR build lists this package as not available for aarch64. Could the aarch64 tag be added to the AUR if it was verified to build correctly?

`==> ERROR: mousai is not available for the 'aarch64' architecture`

**Comment by SeaDve** [comment]
Closing it since there's nothing I can do from here. Thanks!
