### ISSUE TITLE
Croatian localized texts on Apps for GNOME webpages not used

### ISSUE THREAD

**Issue by milotype** [SeaDve/Mousai#37]
Please check why _summary_ and _description_ texts for **Mousai** don't translate into the Croatian localized versions at https://apps.gnome.org/hr/ as well as at https://apps.gnome.org/hr/app/io.github.seadve.Mousai/ (it does work for instance for German).

The Croatian translation of the app is complete at [Weblate](https://hosted.weblate.org/languages/hr/kooha/).

The Croatian localized version does work for **Kooha** (https://apps.gnome.org/hr/app/io.github.seadve.Kooha/)

**Comment by SeaDve** [comment]
I am not sure how translations work on Apps For GNOME, but it may be the website is not yet updated

**Comment by SeaDve** [comment]
I'm gonna close this since I cannot do anything to fix it from here. Maybe submit an issue there. Thanks!
