### ISSUE TITLE
The app just freezes when it doesnt recognize a song - Pop!_OS

### ISSUE THREAD

**Issue by Benjamin5678** [SeaDve/Mousai#39]
The app works fine if you play a song it recognizes but if you dont play a song or play a song it doesnt recognize it freezes. I imagine it has a timeout where it provides an error but its not working right. I'm on PopOs and I also attached a screen recording with the bug and a neofetch. Im using version 0.6.6 stable branch installed from flatpak. Let me know if there's any other information I should provide. Thank you!

https://user-images.githubusercontent.com/42218528/144735557-424b2413-2f6a-444f-85b5-6b4197c2276b.mp4

**Comment by SeaDve** [comment]
The logs may be helpful

**Comment by SeaDve** [comment]
Hi, a lot of fixes has happen in the main branch, especially on the backend, which likely solve this issue. Feel free to reopen this when it is still not fixed.
