### ISSUE TITLE
Specify audio input source

### ISSUE THREAD

**Issue by onny** [SeaDve/Mousai#4]
Hey,
it would be cool to choose the source for audio recognition. For example, besides recording with microphone, one could also record the system sound directly.
Best regards
Jonas

**Comment by SeaDve** [comment]
This is already possible, as it follows the default source in the GNOME Settings. (Now sure witk other DE) Although, you might have to unplug the microphone.

**Comment by hadess** [comment]
> This is already possible, as it follows the default source in the GNOME Settings. (Now sure witk other DE) Although, you might have to unplug the microphone.

The system sound (what's being played back on the default output) isn't a possible source of audio in the sound settings. My desktop machine has no builtin microphone, so I see the muted microphone icon, and an error message after that (https://github.com/SeaDve/Mousai/issues/20)
