### ISSUE TITLE
Flatpak: desktop icon not transparent

### ISSUE THREAD

**Issue by alexrelis** [SeaDve/Mousai#46]
![mousai](https://user-images.githubusercontent.com/17351598/162592587-e5fafc5d-60d6-4f0f-b5ae-bfa2bc3b0b62.png)
The icon is not transparent when I open it in KDE Plasma, which is weird because the file in `/var/lib/flatpak/app/io.github.seadve.Mousai/x86_64/stable/2439ff5c96f580d12a5f28e9b91f24d0055039894be62ef52d9857da935689a8/files/share/icons/hicolor/scalable/apps/io.github.seadve.Mousai.svg` is transparent when I open it manually. Small nitpicky issue, I know. But I just thought I'd do my part by submitting this.

Other information:

OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.16.0-0.bpo.4-amd64 
DE: Plasma 5.20.5 
WM: KWin 
Theme: Breeze
Theme: Breeze [Plasma], Breeze [GTK2/3] 
Icons: breeze [Plasma], breeze [GTK2/3]

**Comment by SeaDve** [comment]
That's likely an issue with your DE

**Comment by SeaDve** [comment]
Closing it, since I don't think there's something I can do from here to fix it.

**Comment by n3thshan** [comment]
> However, I clean up the svg icons, if that fixes it

Just downloaded the app on KDE Plasma 6.5. The issue still persists. If you could, what does this mean? How do i clean up the ```svg``` icons?

**Comment by tibequadorian** [comment]
Tried removing elements and removing clipPath elements helped: [io.github.seadve.Mousai.svg](https://github.com/user-attachments/assets/c75acefd-4fea-4945-9259-6fd36ed652c9)
```diff
11,13d10
<     <clipPath id="c">
<         <rect height="152" width="192"/>
<     </clipPath>
27,29d23
<     <clipPath id="g">
<         <rect height="152" width="192"/>
<     </clipPath>
32c26
<     <g clip-path="url(#c)" mask="url(#b)" transform="matrix(1 0 0 1 -8 -16)">
---
>     <g mask="url(#b)" transform="matrix(1 0 0 1 -8 -16)">
37c31
<     <g clip-path="url(#g)" mask="url(#f)" transform="matrix(1 0 0 1 -8 -16)">
---
>     <g mask="url(#f)" transform="matrix(1 0 0 1 -8 -16)">
```
