### ISSUE TITLE
Export / Get list of found songs

### ISSUE THREAD

**Issue by tristanvigar** [SeaDve/Mousai#48]
Is there an easy way to get access to the song history list outside of the UI? Perhaps via the filesystem (Like text or json stored in a data folder)? I've looked over the code but was unsuccessful in finding an answer since I'm unfamiliar with GTK/Rust. If I understand correctly, I'm trying to find where else I can access Application::default().settings().string("history") from outside of Mousai. Is that possible?

Thanks so much! Mousai is a stellar app!

**Comment by SeaDve** [comment]
It can be access in plain text through the key file. It is `~/.var/app/io.github.seadve.Mousai/config/glib-2.0/keyfile` for flatpak

**Comment by tristanvigar** [comment]
That's perfect! Thank you so much!
