### ISSUE TITLE
Landing page / Website request

### ISSUE THREAD

**Issue by aha999** [SeaDve/Mousai#49]
It would be useful to have this project's landing site / website, so any future news articles can link to it and the website would make a better visual representation of the project that could attract more users, developers and contributors.

A simple and free option is via [Github Pages](https://pages.github.com/), that a lot of github open source projects are using, which Github hosts for any repo on their website.

> Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
> No databases are needed to be set up and no servers to configure

Repositories that use github pages: [Examples](https://github.com/collections/github-pages-examples)

Interesting article: [Link](https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare)

> Consider [Jekyll](https://jekyllrb.com/). You give it [Liquid](https://jekyllrb.com/docs/liquid/) templates and Markdown content
> Free Jekyll templates: https://jekyllthemes.io/free

**Comment by SeaDve** [comment]
Thats would be indeed nice to have. Unfortunately, I don't think I have the resource to maintain and develop it. However, sinve Mousai is part of GNOME Circle it is included in https://apps.gnome.org/app/io.github.seadve.Mousai/

**Comment by SeaDve** [comment]
Closing this as unplanned, since the `README` in the root, I think, already provides those information, and there's https://apps.gnome.org/app/io.github.seadve.Mousai/
