### ISSUE TITLE
Better design for the welcome and/or empty state

### ISSUE THREAD

**Issue by SeaDve** [SeaDve/Mousai#5]
This is what it currently looks like:
![This is what it currently looks like](https://user-images.githubusercontent.com/64297935/114289185-70a55a00-9aa8-11eb-9a92-38e14450f500.png)

It would be better if there is a more colorful artwork for the welcome state to comply with the HIG.

**Comment by liimee** [comment]
![a](https://user-images.githubusercontent.com/70614549/114299198-44a7ca00-9ae4-11eb-9a5b-9faf89591b4b.png)
or
![b](https://user-images.githubusercontent.com/70614549/114299205-4a9dab00-9ae4-11eb-9104-362f304ac0e3.png)
these are so random lol...

imo the current one looks ok

**Comment by SeaDve** [comment]
Thanks! That looks great. 

Although, what I mean is similar to gnome tour's artwork.
![image](https://user-images.githubusercontent.com/64297935/114344208-fc46e580-9b91-11eb-8d15-ba2cb3deeec5.png)

But, yours could seem to fit, not sure though if it will scale well.

**Comment by liimee** [comment]
oh, I see
hold on :)

> But, yours could seem to fit, not sure though if it will scale well.

GitHub doesn't support svg?

**Comment by SeaDve** [comment]
Unfortunately, nope. Although, you can copy paste the source code to a gist.

**Comment by liimee** [comment]
https://gist.github.com/liimee/fa6be75cae0aaf6c207956272dba03ce
it's pretty big :sweat_smile:

**Comment by SeaDve** [comment]
It looks good but it is still raster graphics that is stored in svg

**Comment by SeaDve** [comment]
![welcome_page](https://user-images.githubusercontent.com/64297935/114388443-45189180-9bc6-11eb-86fd-b09a004a81d6.png)

I tried this but I don't think it fits well

**Comment by liimee** [comment]
> It looks good but it is still raster graphics that is stored in svg

my bad, apologies


> ![welcome_page](https://user-images.githubusercontent.com/64297935/114388443-45189180-9bc6-11eb-86fd-b09a004a81d6.png)
> 
> I tried this but I don't think it fits well

looks pretty good
