### ISSUE TITLE
Images on landing page not loading

### ISSUE THREAD

**Issue by ghost** [SeaDve/Mousai#52]
On https://apps.gnome.org/app/io.github.seadve.Mousai/ it doesn't show up any images.

For example: https://apps.gnome.org/assets/screenshots/io.github.seadve.Mousai/Mousai-screenshot2.png says: `The image “https://apps.gnome.org/assets/screenshots/io.github.seadve.Mousai/Mousai-screenshot2.png” cannot be displayed because it contains errors.`

Using Firefox 91.7.0esr (64-bit)

**Comment by SeaDve** [comment]
This is likely since the path to screenshots has changed since the last release. It would be fixed when I create a new release in flathub.

**Comment by SeaDve** [comment]
This should be fixed now.
