### ISSUE TITLE
UI glitch when clicking settings button

### ISSUE THREAD

**Issue by akash-258** [SeaDve/Mousai#53]
Installed app as a flatpak, when I click on settings button, this weird ui thing happens.

![mousai](https://user-images.githubusercontent.com/43058609/172054731-bf8032b8-ed29-422e-886c-a309d78488b9.png)

**Specs**:
OS: Linux Mint 20.3 x86_64 
Kernel: 5.15.0-33-generic
DE: Cinnamon

Graphics:  
Device-1: AMD Picasso driver: amdgpu v: kernel bus ID: 07:00.0 chip ID: 1002:15d8 
                 Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
                               resolution: 1920x1080~60Hz 
                 OpenGL: 
                 renderer: AMD Radeon Vega 11 Graphics (RAVEN DRM 3.42.0 5.15.0-33-generic LLVM 12.0.0) 
                 v: 4.6 Mesa 21.2.6 direct render: Yes
                 
Flatpak version : 1.12.2
Mousai version : 0.6.6

**What worked :** 
when launching the application with this command  `AMD_DEBUG=nodcc flatpak run io.github.seadve.Mousai` , everything is working perfectly

**Comment by SeaDve** [comment]
Does this also happen with other libadwaita + gtk4 applications?

**Comment by akash-258** [comment]
Yes, the same things happen with other apps as well, but i have to check if it happens with only flatpak apps, or all of them

**Comment by akash-258** [comment]
Solved it by replacing the desktop file's exec command located here `/var/lib/flatpak/exports/share/applications` with
```
sh -c "AMD_DEBUG=nodcc /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mousai io.github.seadve.Mousai"
```

**Comment by akash-258** [comment]
This problem did not happen with cinnamon on arch linux. It's only happening in linuxmint.

**Comment by SeaDve** [comment]
I think this must be an upstream issue then, and I can't do much from Mousai's side.

**Comment by akash-258** [comment]
I will update here if I find a decent solution.

**Comment by SeaDve** [comment]
> I will update here if I find a decent solution.

Thanks!
