### ISSUE TITLE
Failed to create element from factory name

### ISSUE THREAD

**Issue by abinlatheef** [SeaDve/Mousai#54]
Shows 'Failed to create element from factory name' when clicken on listen.

**Comment by SeaDve** [comment]
Was Mousai installed through Flatpak?

**Comment by SeaDve** [comment]
Also, can you paste the output of the following command:

`gst-inspect-1.0 pulsesrc | cat && gst-inspect-1.0 audioconvert | cat && gst-inspect-1.0 level | cat && gst-inspect-1.0 encodebin | cat`

**Comment by abinlatheef** [comment]
It is installed from the AUR

**Comment by abinlatheef** [comment]
It now shows 'Failed to make pulsesrc'.

**Comment by abinlatheef** [comment]
Ooh it was `gst-plugins-good`. But why isn't that automatically pulled as a dependency at install then?
Also I don't have pulseaudio installed fyi. Thank you btw.
