### ISSUE TITLE
Could not find the icon 'io.github.seadve.Mousai-ltr'

### ISSUE THREAD

**Issue by dotlambda** [SeaDve/Mousai#6]
After updating to 0.3.2, I get

`(io.github.seadve.Mousai:3808022): Gtk-WARNING **: 11:48:28.278: Could not find the icon 'io.github.seadve.Mousai-ltr`

**Comment by SeaDve** [comment]
Thanks for reporting! Are there any other logs? What are the bugs in the user space, if there are any such as visual?

**Comment by dotlambda** [comment]
I was able to fix it. I just had to install the hicolor theme.
