### ISSUE TITLE
[FEATURE REQUEST] Export option.

### ISSUE THREAD

**Issue by Giger22** [SeaDve/Mousai#73]
Could you add option to export songs to .txt file?

**Comment by SeaDve** [comment]
Current development version provides a way to copy song/s into some text. Could I know some use case of saving the copied text into a file?

**Comment by Giger22** [comment]
Backup.

**Comment by SeaDve** [comment]
I'm gonna close this since this feature is not planned.

**Comment by Giger22** [comment]
Sad!
I meant something like export to .csv like in [SongRec](https://www.addictivetips.com/app/uploads/2021/10/songrec-1.jpg) application.
