### ISSUE TITLE
Missing select icon

### ISSUE THREAD

**Issue by aronkvh** [SeaDve/Mousai#76]
On KDE Plasma the select icon is missing.
Mousai 0.7.0
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Themes are default.
![image](https://user-images.githubusercontent.com/57704946/230671578-eca91037-7390-400d-8f57-c880912efa48.png)

Otherwise the newest update is really nice :)

**Comment by SeaDve** [comment]
Oh, it seems KDE doesn't have a corresponding icon for that
