### ISSUE TITLE
Don't allow forward swipe navigation in history view

### ISSUE THREAD

**Issue by imhemish** [SeaDve/Mousai#79]
[Kooha-2023-04-08-16-21-02.webm](https://user-images.githubusercontent.com/74466492/230718464-f8280148-fbeb-4d40-84e6-087d9a46fc9c.webm)

See this recording, when I click on a track's cover, it sends me to track's information, and i can swipe back reach the history view again. But on history view, swiping forward is allowed, which should not be the case. Because swiping forward takes you to last track's info you viewed. Going forward should only be done when clicking on some cover art.

So the leaflet's ```can-navigate-forward``` should be set to ```false```.

I could have just made a pull request about it, but I thought first it should be discussed here.

**Comment by SeaDve** [comment]
That was actually a feature

It took me actually days to implement that with: https://github.com/SeaDve/Mousai/commit/4f7cebaf84ce825377488c5f469992305280003d

**Comment by imhemish** [comment]
> That was actually a feature
> 
> It took me actually days to implement that with: [4f7ceba](https://github.com/SeaDve/Mousai/commit/4f7cebaf84ce825377488c5f469992305280003d)

I get the swiping factor, with a leaflet, but swiping forward on history view does not seem natural. Cuz it would show the song info you last viewed and in my opnion, that should be invoked only by clicking on respective cover art. Sure, going back is expected, but not forward.

**Comment by SeaDve** [comment]
I do see the forward swipe as reversing the "Go Back" Button

**Comment by imhemish** [comment]
> I do see the forward swipe as reversing the "Go Back" Button

It's fine if you want to keep that

**Comment by SeaDve** [comment]
It's also something useful when you accidentally go back, but forget what song was selected before.

Another thing is it feels more natural when you have multiple songs opened in stack, which you can navigate through like:

`A <-> B <-> C`

instead of just

`A <- B <- C`

**Comment by imhemish** [comment]
> It's also something useful when you accidentally go back, but forget what song was selected before.
> 
> Another thing is it feels more natural when you have multiple songs opened in stack, which you can navigate through like:
> 
> `A <-> B <-> C`
> 
> instead of just
> 
> `A <- B <- C`

I understood that your point, just curious how multiple songs would be there in stack? I can only open one at moment and then go back.

**Comment by SeaDve** [comment]
The maximum possible I think is 2: you can open another one if you click the song on the song bar, while there is already an open one.

I do plan in the future showing songs from the same artist/album, so it may be possible to have theoretically infinite in the future.
