### ISSUE TITLE
Mousai crashes when selecting a song

### ISSUE THREAD

**Issue by rene-coty** [SeaDve/Mousai#85]
When I select a song from the main page using the select button, the app crashes and I have to relaunch it. Same bug occurs when I right-click on a song, or when I choose the 'Select all' option above. So it's related to selection specifically..
Here is a recording showing the issue:
[Capture vidéo du 2023-05-02 09-40-13.webm](https://user-images.githubusercontent.com/95506494/235607813-89166e9b-e847-4a4d-a506-fb93bc203614.webm)
Here is the output on Console:
![Capture d’écran du 2023-05-02 09-34-18](https://user-images.githubusercontent.com/95506494/235606716-54cc322a-7ac4-4806-a439-4222aa1d5b70.png)

**Comment by SeaDve** [comment]
I think I might have figure it out. If you used different locale, other than `en_US`, the translation may have translated the string incorrectly.

**Comment by rene-coty** [comment]
> could you provide extra information about your system, specifically the one asked in the issue template?

Sorry I forgot to mention these:
- io.github.seadve.Mousai 0.7.4
- Flatpak: true

- Distribution: GNOME 44 (Flatpak runtime)
- Desktop Session: gnome
- Display Server: wayland

- GTK 4.10.3
- Libadwaita 1.3.2
- Libsoup 3.4.1
- GStreamer 1.20.6
> It would also be useful to add RUST_BACKTRACE=1 before the command to run Mousai

![Capture d’écran du 2023-05-02 10-30-16](https://user-images.githubusercontent.com/95506494/235617854-d5f83786-fc92-44e2-afb9-1559b10c30bd.png)

**Comment by SeaDve** [comment]
Do you use a different locale, other than the default?

**Comment by rene-coty** [comment]
Yes, French (fr)

**Comment by SeaDve** [comment]
I'll do a release today. Hopefully, that should fix it

**Comment by SeaDve** [comment]
You could test the new version early using the following command:
```
flatpak install --user https://dl.flathub.org/build-repo/21338/io.github.seadve.Mousai.flatpakref
```
