### ISSUE TITLE
Android Release

### ISSUE THREAD

**Issue by Anvil5465** [SeaDve/Mousai#87]
I'm not sure how feasible this is, but I would really love it if this were available as an apk for Android if possible, since there are currently no open source music recognition apps for Android that I am aware of.

**Comment by SeaDve** [comment]
I'd also really like to have an Android version. However, the underlying libraries, GTK, LibAdwaita, etc. do not support Android.

**Comment by SeaDve** [comment]
Closing this as not planned, since I don't think GTK, etc. would have Android support anytime soon

Though, I would keep this in mind once the ecosystem gaind Android support
