### ISSUE TITLE
Snap Package Ready and Working

### ISSUE THREAD

**Issue by soumyaDghosh** [SeaDve/Mousai#92]
Hii, I have created a snap package for this amazing app. Would you like to publish it under your name in the snap-store. I will maintain this anyways.

**Comment by SeaDve** [comment]
Hello. That's nice! Feel free to use yours as the publisher

**Comment by soumyaDghosh** [comment]
Thank you, it's in the review queue. Thanks. These are the badges to publicise,

HTML:
```
<a href="https://snapcraft.io/mousai">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>
```

MD:
```
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/mousai)
```

**Comment by soumyaDghosh** [comment]
Hi, the snap package has been published, you can publicise it now.

**Comment by SeaDve** [comment]
Thanks for the heads up! I added a section on readme for it via commit https://github.com/SeaDve/Mousai/commit/0f28b1cbc216f3d036523f55bb0321d6e395941d
