### ISSUE TITLE
mousai is not listen to any music

### ISSUE THREAD

**Issue by smarthaleem** [SeaDve/Mousai#97]
**Affected version**

- io.github.seadve.Mousai 0.7.5 
- Flatpak: false  
- Language: en_NG, en, en, C  

- Distribution: Ubuntu Core 22 
- Desktop Session: ubuntu 
- Display Server: wayland  

- GTK 4.10.4 
- Libadwaita 1.3.3 
- Libsoup 3.4.2 
- GStreamer 1.20.3

**Bug summary**

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

**Comment by SeaDve** [comment]
Can you provide logs about what happened? The instructions on how to get them is in the issue template

**Comment by SeaDve** [comment]
Seeing that you are Ubuntu core, I think you may have missing services on your system, like pulseaudio

**Comment by SeaDve** [comment]
> I got it. He is using the snap, and I have mentioned that playing the music is not supported in the snap. And though this is not entirely correct, but some extensions don't work, like `mpeg`.
> 
> ```
> 2023-09-28T13:26:04.410507Z  WARN mousai::player: Received warning message: Error { domain: gst-play-error-quark, code: 0, message: "Warning from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: There is no codec present that can handle the stream's type.\nNo decoder available for type 'audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2'.\n../gst/playback/gsturidecodebin.c(960): unknown_type_cb (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0" } details=None
> 2023-09-28T13:26:04.410543Z ERROR mousai::player: Received error message: Error { domain: gst-play-error-quark, code: 0, message: "Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.\nYour GStreamer installation is missing a plug-in.\n../gst/playback/gsturidecodebin.c(1027): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:\nno suitable plugins found:\nMissing decoder: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)2, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)1210, rate=(int)44100, channels=(int)2)\n" } state=Buffering details=None
> ```
> 
> This is the error log we get when I try to play mpeg songs. I haven't got any way to add the mpeg dependencies.

You probably need to package `gst-plugins-good`

**Comment by SeaDve** [comment]
I'll close this for now, but feel free to re-open once the needed information is given.
