### ISSUE TITLE
Untranslatable strings in inspector-page.ui

### ISSUE THREAD

**Issue by sabriunal** [SeaDve/Mousai#98]
Hi, there are a few untranslatable strings in the inspector-page.ui.

Could you mark them as translatable if they are visible to users. 

- https://github.com/SeaDve/Mousai/blob/main/data/resources/ui/inspector-page.ui#L11-L12
- https://github.com/SeaDve/Mousai/blob/main/data/resources/ui/inspector-page.ui#L15
- https://github.com/SeaDve/Mousai/blob/main/data/resources/ui/inspector-page.ui#L25
- https://github.com/SeaDve/Mousai/blob/main/data/resources/ui/inspector-page.ui#L35
- https://github.com/SeaDve/Mousai/blob/main/data/resources/ui/inspector-page.ui#L49

**Comment by SeaDve** [comment]
Thanks for reporting! Though, these currently should only be visible to developers, so I decided before to not mark them as translatable as it is not part of the actual interface the user should interact.

I'll closing this as not planned
